### ISSUE TITLE
Turtle serialization problems (release 2016-11-17)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#237]
@siuc-nate, the serializations including the landing page are looking much better. There are some problems with the turtle serialization (no. 2-4 below). I discovered these 3 problems by downloading the turtle file, loading it into the app at http://rdf-translator.appspot.com/ and trying to convert from N3 (turtle) to RDF/XML or JSON (or any other serialization).  You can tell if you have valid RDF since this app will and throw an error and fail to convert if the source code is not valid RDF. While a bit tedious to validate the RDF using this app, it is doable. 

#### SERIALIZATION NAV MENU:

 (1) The current turtle is not a "context" (so menu label wrong), but rather the serialization of the Terms (turtle: ceterms) "schema".

 (2) The "Turtle" serialization needs to have each of its sets of concepts broken out into separate "schemes" (e.g., ActionStatus, AgentSector etc.). So you have the (properties/classes) schema (ceterms) as turtle and you have each of the separate concept schemes as turtle. 

Suggest something like:

```
CTDL JSON-LD Context
CER JSON Schema
Turtle Encodings:
    CTDL Properties & Classes
    Concept Schemes:
         Action Status 
         Agent Sector
         Assessment Method
         Assess Use
         Audience
         Audience Level
         Claim Type
         CostType
         Credential Status
         Credit Unit
         Delivery Type
         External Input Type
         Learn Method
         Intended Purpose
         Residency
         Score Method
         ServiceType
```
#### ENCODING ERRORS (turtle):
  (3) Erroneous "hidden" undeclared prefix starting at line 41 "hidden:MajorEntity" and repeated throughout.

  (4) "lrmi" undeclared prefix at line 701 (needs: prefix http://purl.org/dcx/lrmi-terms/)

  (5)  Error at line 840 -- complete "skos" text with "skos:broadMatch"

```
    ctdl:broadAlignment a rdf:Property ;
           ...
           owl:equivalentProperty asn:broadAlignment skos ; (line840)
```

 (6) You are getting an error at line 2203 that "actionStat" is not "bound", i.e., it has no prefix declaration. That is true with all of the concept terms starting at that line to the bottom of the file (line 2832). BUT, you **should NOT add these concept namespace prefixes** to this this turtle file since none of them belong here. Each set of vocabulary concepts needs a SEPARATE turtle file as noted under MENU(2) above. **See issue #236 for example encoding of a single concept scheme in turtle.**

I have uploaded a corrected turtle file here (.ttl changed to .txt to satisfy Github): [ctdl-schema-rev.txt](https://github.com/CredentialTransparencyInitiative/vocabularies/files/613458/ctdl-schema-rev.txt)

**Comment by siuc-nate** [comment]
Some of these issues are already solved, but I am leaving this open so I can compare it against the updated serializations system.

**Comment by stuartasutton** [comment]
@siuc-nate, see [Badge](http://www.credreg.net/ctdl/terms#Badge) and you'll see it still shows subclass of "hidden:MajorEntity".

**Comment by siuc-nate** [comment]
My mistake, forgot to remove it from the release copy - this is fixed.

**Comment by siuc-nate** [comment]
I have corrected the issues listed in the original post.
